test = read.csv(file = 'data/test.csv')
train = read.csv(file = 'data/train.csv')
test = data.frame(test)
train = data.frame(train)
train$Survived = as.factor(train$Survived)
train$Pclass = as.factor(train$Pclass)
test$Pclass = as.factor(test$Pclass)
#write.table(head(test),sep = " | ")
library(ggplot2)
#plot = ggplot(train)+
#+ geom_bar(mapping=aes(x=Pclass,fill=Survived))
# png("pclass.png")
# print(plot)
# dev.off()

